export const categories = [
  '3D',
  'Animated Video Generator',
  'Art',
  'Audio Editing',
  'Avatars',
  'Cloned voiceover',
  'Code Assistant',
  'Copywriting',
  'Customer Support',
  'Design Assistant',
  'Developer Tools',
  'Education Assistant',
  'Email Assistant',
  'Experiments',
  'Fashion',
  'Fun Tools',
  'Gaming',
  'General Writing',
  'Gift Ideas',
  'Healthcare',
  'Human Resources',
  'Image Editing',
  'Image Generator',
  'Legal Assistant',
  'Life Assistant',
  'Logo Generator',
  'Low-code/no-code',
  'Memory',
  'Music',
  'Paraphraser',
  'Personalized Videos',
  'Photo',
  'Productivity',
  'Prompts',
  'Real Estate',
  'Research',
  'Resources',
  'SEO',
  'SQL',
  'Sales',
  'Search Engine',
  'Social Media Assistant',
  'Spreadsheets',
  'Startup',
  'Story Teller',
  'Summarizer',
  'Text To Speech',
  'Text to Animated Video',
  'Text to Voice Over and Video',
  'Text',
  'Transcriber',
  'Video Creation and Editing',
  'Video Editing',
  'Video Generator',
  'Video Planner',
  'Voiceover + avatar',
]
