import './globals.css'
import { Inter } from 'next/font/google'
import clsx from 'clsx'

import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={clsx(inter.variable, 'h-full  font-sans antialiased ')} suppressHydrationWarning>
      <body className="flex h-full flex-col bg-neutral-2 text-neutral-12 dark:bg-neutralDark-1 dark:text-neutralDark-12">
        <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
